#pragma once
#include "CoreMinimal.h"
#include "GameFramework/CheatManager.h"
#include "CheatEventDelegate.h"
#include "Templates/SubclassOf.h"
#include "FSDCheatManager.generated.h"

class AActor;
class AFSDAIController;
class APawn;
class APlayerCharacter;
class UBaseCritterDescriptor;
class UEnemyDescriptor;
class UItemID;
class UObject;
class UPlayerCharacterID;
class UResourceData;
class UWidget;
UCLASS(Blueprintable)
class ROGUECORE_API UFSDCheatManager : public UCheatManager {
    GENERATED_BODY()
public:
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FShowPawnHealthDelegate, bool, InShow);
    
    UPROPERTY(BlueprintAssignable, BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FShowPawnHealthDelegate OnShowPawnHealth;
    UPROPERTY(BlueprintReadWrite, EditAnywhere, Transient, meta=(AllowPrivateAccess=true))
    bool bShowPawnHealth;
 
    int32 RoomJumpCount;
    float PreviousMaxDistanceBeforeCleanup;
    bool UnlimitedScoutFlareDuration;
    FCheatEvent ToggleHoopGameMovement;
    FCheatEvent OnShowLevelTimeDebugText;
    AActor* SpawnPosMarker;
    bool EscortShowSmartRockDebug;
    bool IsUsingSavedCheats;
    UFSDCheatManager();
    UFUNCTION(BlueprintCallable)
    void SwitchCharacter(UPlayerCharacterID* characterID);
    void SpawnEnemies(UEnemyDescriptor* descriptor, int32 count);
    void SpawnCritters(UBaseCritterDescriptor* descriptor, int32 count);
    UFUNCTION(BlueprintCallable, Exec)
    void SpawnBosco(TSoftClassPtr<APawn> DroneClass, TSubclassOf<AFSDAIController> aControllerClass);
    void ShowTutorialDebug();
    void ShowPawnHealth(bool InShow);
    void SetStandingDown(bool standingDown);
    void SetSpawnEnemies(bool NewSpawnEnemies);
    static bool SetSavedCheatValue(const FName CheatName, const int32& ValueToSet);
    void SetQuadPickAxe(bool Quad);
    void SetHUDVisible(bool ShowHUD);
    void SetGodMode(bool God);
    void SetFastMovement(bool fast);
    static void SetActorTrackingCheat(AActor* Actor, bool shouldTrack);
    UFUNCTION(BlueprintCallable, Reliable, Server)
    void Server_ResetCritChance(APlayerCharacter* Character);
    UFUNCTION(Server, Reliable)
    void Server_Refresh_Daily_Special(int32 Index);
    void ResetSpacerigIntroMessage();
    void R_RemoveResources(int32 Number);
    void R_RemoveCredits(int32 Number);
    void R_RemoveCraftingResource(int32 amount, int32 Type);
    void R_Expansion_AddShards(int32 amount);
    void R_Chips_Set(int32 amount);
    void R_Chips_Add(int32 amount);
    void R_AddSeasonToken(int32 Number);
    void R_AddResources_Player(float Number);
    void R_AddResources(float Number);
    void R_AddPerkPoints(int32 amount);
    void R_AddMatrixCores(int32 Number);
    void R_AddHollomite(float amount);
    void R_AddGymCredit(int32 Type, int32 amount) const;
    void R_AddGold(float amount);
    void R_AddDystrum(float amount);
    void R_AddCredits(int32 Number);
    void R_AddCraftingResource(int32 amount, int32 Type) const;
    void R_Add_Phazyonite(int32 amount);
    void R_Add_BitterGem(int32 amount);
    void R_Add_Aquarq(int32 amount);
    UFUNCTION(BlueprintCallable, BlueprintPure)
    bool IsSpawnEnemiesEnabled() const;
    bool IsInGodMode();
    bool IsFlyModeActive() const;
    bool IsFastMovementActive() const;
    static bool GetSavedCheatValue(const FName CheatName, int32& ValueToGet);
    void GetListOfRoomNames(TArray<FString>& roomNames);
    static UWidget* GetFocusedUMGWidget();
    UFUNCTION(BlueprintCallable, Exec, meta=(WorldContext="WorldContextObject"))
    void Expansion_ResetSave(UObject* WorldContextObject) const;
    void Expansion_LevelUp() const;
    void Expansion_AddXP_Player(int32 amount) const;
    UFUNCTION(BlueprintCallable, Exec, BlueprintPure=false)
    void Expansion_AddXP(int32 amount) const;
    void Expansion_AddShards(UObject* WorldContextObject, int32 amount) const;
    void DestroyAllInstances(TSubclassOf<AActor> destroy);
    void D_Rejoin_RestoreState();
    void D_MovieModeStartWithCameraShake(bool Value);
    void D_MovieModeStartAtOrigin(bool Value);
    void D_EnableMovieModeInSpacerig(bool Value);
    void D_EnableMovieMode(bool Value);
    void CopySeedForStage();
    void CompleteRandomIntelChallenges(const int32 AmountToComplete) const;
    void ClaimIntelObjectives() const;
    void ClaimIntelChallenges() const;
    UFUNCTION(BlueprintCallable, meta=(WorldContext="WorldContextObjectm"))
    static void Cheat_UnlockWeapon(UObject* WorldContextObjectm, UItemID* ItemID);
    UFUNCTION(BlueprintCallable, meta=(WorldContext="WorldContextObject"))
    static void Cheat_UnlockAllWeapons(UObject* WorldContextObject);
    static void Cheat_UnlockAllUpgrades(UObject* WorldContextObject);
    static void Cheat_UnlockAll_Poses(UObject* WorldContextObject);
    static void Cheat_UnlockAll_Beers(UObject* WorldContextObject);
    void Cheat_SetSpawnPosMarker(AActor* Actor);
    static void Cheat_Schematic_UnlockAll(UObject* WorldContextObject);
    static void Cheat_Schematic_ResetAll(UObject* WorldContextObject);
    static void Cheat_Schematic_GiveRandom(UObject* WorldContextObject);
    static void Cheat_Schematic_ForgeAll(UObject* WorldContextObject);
    static void Cheat_Resources(UObject* WorldContextObject, float amount);
    static void Cheat_ResetEquippedUpgrades(UObject* WorldContextObject);
    static void Cheat_RemoveResources(UObject* WorldContextObject, int32 amount);
    static void Cheat_PickAxeVanity_UnlockAll(UObject* WorldContextObject);
    static void Cheat_PickAxeVanity_ResetAll(UObject* WorldContextObject);
    static void Cheat_MinersManual_ShowAll(UObject* WorldContextObject);
    static void Cheat_GenerateNewMissionSeed(UObject* WorldContextObject, bool Enabled);
    static void Cheat_ForceTreasure(UObject* WorldContextObject);
    static void Cheat_ForceLostPack(UObject* WorldContextObject);
    static void Cheat_Campaign_Complete(UObject* WorldContextObject);
    static void Cheat_Campaign_Advance(UObject* WorldContextObject);
    static void Cheat_AddXP(UObject* WorldContextObject, int32 amount);
    static void Cheat_AddPerkPoints(UObject* WorldContextObject, int32 amount);
    static void Cheat_AddCredits(UObject* WorldContextObject, int32 amount);
    void C_Windows_PrintStack() const;
    void C_Windows_CloseAll() const;
    void C_VanityMasteryResetXP();
    void C_VanityMasteryAddXP(int32 Number);
    void C_UnlockOverclocking();
    void C_UnlockAll_WeaponUpgrades();
    void C_UnlockAll_WeaponSkins_Paintjobs();
    void C_UnlockAll_WeaponSkins_Frameworks();
    void C_UnlockAll_WeaponSkins();
    void C_UnlockAll_Weapons();
    void C_UnlockAll_StoreVanity();
    void C_UnlockAll_Poses_ForAll();
    void C_UnlockAll_Poses();
    void C_UnlockAll_PickaxeParts();
    void C_UnlockAll_Enhancements();
    void C_UnlockAll_Drinks();
    void C_UnlockAll_Beers();
    void C_UnlockAll_ArmorMats();
    void C_UnlockAll();
    void C_Tutorials_ResetHints();
    void C_Treasures_Track(int32 Mode);
    void C_Treasures_Reward(int32 count);
    void C_ToggleWaveTimeDebugText();
    void C_ToggleHoopGameMovement();
    void C_ToggleFadingEnabled();
    void C_ToggleFadingDebug();
    void C_ToggleCanShowBlood();
    void C_TestNegotiationDistribution(int32 TestTimes);
    void C_TestGenerationDesync();
    void C_StopMovement(bool shouldMove);
    void C_SpawnScriptedWaveIndex(int32 Index);
    void C_SpawnScriptedWave();
    void C_SpawnNormalWave();
    void C_SpawnEvenRewarder();
    void C_SpawnBXEDrone(TSoftClassPtr<APawn> DroneClass);
    void C_SpawnBarrelOnPlayer(int32 amount);
    void C_SpawnAllParticles();
    void C_Shouts_SetVoicePitch(float InPitch);
    void C_SetUseSavedCheatsByDefault(bool useSavedCheats);
    void C_SetTestingCharacter(UPlayerCharacterID* characterID);
    void C_SetSavedCheats();
    void C_SetPlayers(int32 Number);
    void C_SetInstantUsables(bool Value);
    void C_SetHostileReadingEnabled(bool Enabled);
    void C_SetHealth(float Health);
    void C_SetFlyMode(bool flyEnabled);
    void C_SetFastFlares();
    void C_SetEnglish(int32 Val);
    void C_SetDancing(bool shouldDance);
    void C_SetArmor(float Armor);
    void C_SetAmmoCostEnabled(bool Enabled);
    void C_Seasons_ResetXP();
    void C_Seasons_ResetToken();
    void C_Seasons_ResetReroll();
    void C_Seasons_ResetPlagueHeartsCollected();
    void C_Seasons_IncrementChallenge(int32 Index);
    void C_Seasons_CompleteScripChallenge(int32 Number);
    void C_Seasons_ClearChallenges();
    void C_Seasons_ClearAllProgress();
    void C_Seasons_AddXP(int32 Number);
    void C_Seasons_AddHeartsCollecdted(int32 Number);
    void C_Seasons_AddChallenge();
    void C_ScoutFlareInfiniteDuration(bool Enabled);
    void C_Schematics_UnlockAll();
    void C_Schematics_ResetAll();
    void C_Schematics_ForgeAll();
    void C_Schematics_ClearHasSeenFirstMessage();
    void C_Schematic_GiveRandom();
    void C_SaveVanitySetupToOpenEditor();
    void C_Salvage_FixMiniMules();
    void C_RevivePlayer();
    void C_Revive();
    void C_Resupply();
    void C_ResetSteamAchievementStats();
    void C_ResetRewardTree();
    void C_ResetForgingXP();
    void C_ResetCheatedResources(int32 newAmount);
    void C_ResetAllBioBoosters();
    void C_ResetAll_Vanity();
    void C_ResetAll_Enhancements();
    void C_ResetAchievements();
    void C_Reset_YearTwoGifts();
    void C_Reset_WeaponSkinsAndUpgrades();
    void C_Reset_WeaponSkins_Paintjobs();
    void C_Reset_WeaponSkins_Framworks();
    void C_Reset_WeaponSkins();
    void C_Reset_Poses();
    void C_Reset_PickaxeParts();
    void C_Reset_Perks();
    void C_Reset_MinersManual();
    void C_Reset_EnemyKillCount();
    void C_Reset_Drinks();
    void C_RemovePlayerRanks(int32 Number);
    void C_RemoveAllWidgets();
    void C_RefreshDailyDeal(int32 Seed);
    void C_Refresh_Daily_Special(int32 Index);
    void C_Refinery_BreakPipes();
    void C_RecordMode();
    void C_Promotion_SetLevelSpecific(APlayerCharacter* onCharacter, int32 Number);
    void C_Promotion_SetLevel(int32 Number);
    void C_Promotion_SetCampaignComplete();
    void C_Promotion_ClearRewardsSeen();
    void C_ProjectileStoreDebugEvents(bool Enabled);
    void C_ProjectilePrintDebugEvents(int32 ID);
    void C_ProjectileDrawPaths();
    void C_ProjectileDebugPrintToggle(bool Enabled);
    void C_PrintLoadout();
    void C_PlayNewMusic(int32 songIndex) const;
    void C_MoveToLastStage();
    void C_MissionMap_Rotate();
    void C_MissionMap_AutoRotate(bool Enabled);
    void C_MinersManual_EnableWorkInProgress(UObject* WorldContextObject);
    void C_MachineEvents_Track(bool track);
    void C_MachineEvents_FinishCurrent();
    void C_KillTeam();
    void C_KillPlayer();
    void C_KillAllFriendly();
    void C_KillAll();
    void C_JumpToNextRoom();
    void C_JetBoots_Enable();
    void C_Intoxication_SetAll(int32 Percent);
    void C_Intoxication_Set(int32 Percent);
    void C_IncrementDifficulty();
    void C_IncrementAllMissionStats(int32 amount);
    void C_GodMode(int32 forceEnable);
    void C_GiveAllGenericHeroItems();
    void C_GameDLC_ResetAnnouncements();
    void C_FSDEvent_SetDebugEvent(const FString& EventName);
    void C_FSDEvent_ListEvents();
    void C_FSDEvent_ClearSeenRewards();
    void C_ForceCrash();
    void C_FixedPLSSeed(int32 Seed);
    void C_FixedMissionSeed(int32 Seed);
    void C_FailMission();
    static void C_FadeFromBlack(UObject* WorldContextObject);
    void C_Facility_SpawnDataCore();
    void C_Facility_DisableShields();
    void C_Escort_ShowSmartRockDebug(bool shouldShow);
    void C_Escort_SetMuleSpeed(UObject* WorldContextObject, float Speed);
    void C_Escort_JumpToNextPhase(UObject* WorldContextObject);
    void C_Escort_AddOilShale(int32 Number);
    void C_DLC_ClearAnnounced();
    void C_DisableBackendEvents();
    void C_DebugTargetEnemySync(bool FindIt);
    static void C_DataTerminal_Activate(UObject* WorldContextObject);
    void C_CompleteStage();
    void C_CompleteRun();
    void C_CompleteObjectives();
    void C_ClearAllMissionStats();
    void C_ClearAllMilestones();
    void C_Character_ResetXP();
    void C_Character_LevelUp(int32 amount);
    void C_Character_AddXP(int32 Number);
    void C_Campaign_ResetProgress();
    void C_Campaign_ResetCompleted();
    void C_Campaign_CompleteMain();
    void C_Campaign_CompleteCurrent();
    void C_Campaign_Advance();
    void C_BXE_StartingWeapons_UnlockAll() const;
    void C_BXE_StartingWeapons_ResetAll() const;
    void C_BXE_SetStatPrintOutEnabled(bool Active);
    void C_BXE_MissionStats_ResetAll();
    void C_BXE_ClearSeenClosedAlphaVideo();
    void C_BiomeEffectsEnabled(bool Enabled);
    void C_AddUncappedXP(int32 amount);
    void C_AddForgingXP(int32 Number);
    void C_AddAllResourcesToInventory(float amount);
    void C_Ability_Unblock();
    void C_Ability_SetNoCooldown(bool Inactive);
    void C_Ability_PrintCooldown(bool Inactive);
    void C_Ability_EnableAtWorkbench(bool Inactive);
    void AddResourceToTeamDeposit(UResourceData* Resource, float amount);
    void AddIntelAndClaimObjectives(const int32 newAmount) const;
    void AddIntel(const int32 newAmount) const;
};
